# appspec.yml (CodeDeploy para EC2/On-Prem)
version: 0.0
os: linux

# Copia todo o artefato para /home/ec2-user/deploy
files:
  - source: /
    destination: /home/ec2-user/deploy

# Ajusta permissões para os scripts
permissions:
  - object: /home/ec2-user/deploy/scripts
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/pre-deploy.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 900
      runas: root
  ValidateService:
    - location: scripts/post-deploy.sh
      timeout: 300
      runas: root
